name: new_super_jumper
description: "Game similar to Doodle jump made with Flutter"
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ">=3.5.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  flame: ^1.22.0
  flame_forge2d: ^0.18.2+3
  shared_preferences: ^2.3.3
  sensors_plus: ^6.1.0
  flame_texturepacker: ^4.1.3
  flame_audio: ^2.1.3  # Added flame_audio package

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true

  assets:
    - assets/images/
    - assets/ui/
    - assets/cats/
    - assets/audio/
    - assets/audio/bg.mp3

  fonts:
    - family: DaveysDoodleface
      fonts:
        - asset: assets/fonts/DaveysDoodleface.ttf

    - family: PixelSix
      fonts:
        - asset: assets/fonts/pixelsix00.ttf
